scrape_configs:
  - job_name: 'MyAppMetrics'
    metrics_path: '/metric/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8100']
        labels:
          application: 'Spring Boot Metric Application'